# -*- coding: utf-8 -*-
"""Copy of E-commerce sales & customer python project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Dg7vCqpvbE9ehmes3VhxAsDM8gNdcfo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("Ecommerce_Sales_Customer_Analytics_Python.csv")

## First 5 rows
df.head()

## last 5 rows
df.tail()

## Number of rows and columns
df.shape

## column names
df.columns

## Data types and information
df.info()

## only datatypes
df.dtypes

## statistical summary
df.describe()

## Categorical summary
df.describe(include="object")

## Unique values
df.nunique()

## unique categories
df["category"].unique()

df["order_status"].unique()

df["payment_method"].unique()

###########    DATA CLEANING       #########
## missing values
df.isnull().sum()

## Missing-value in percentage
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

## duplicates
df.duplicated().sum()

## Remove duplicates
df = df.drop_duplicates().copy()

df.duplicated().sum()

## MISSING VALUE HANDLING
## checking
df.isnull().sum()

## city
df["city"] = df["city"].fillna(df["city"].mode()[0])
df["city"]

## discount
df["discount_pct"] = df["discount_pct"].fillna(
    df["discount_pct"].median()
)
df["discount_pct"]

## Customer rating
df["customer_rating"]= df["customer_rating"].fillna(df["customer_rating"].median())
df["customer_rating"]

## Convert date
df["order_date"] = pd.to_datetime(df["order_date"],errors="coerce")
df["order_date"]

df["order_date"].isnull().sum()

## if there were any missing dates removing those rows
df = df.dropna(subset=["order_date"]).copy()
df

## Final missing-value check
df.isnull().sum()

#############          FILTERING     ##########
## Delivered orders
delivered_orders = df[df["order_status"] == "Delivered"]
delivered_orders.head()

## Orders above ₹5,000
high_value_orders = df[df["final_amount"] > 5000]
high_value_orders.head()

## Multiple conditions
high_value_delivered = df[
    (df["final_amount"] > 5000) &
    (df["order_status"] == "Delivered")
]

high_value_delivered.head()

##########     SORTING    ########
## Highest-value orders
df.sort_values(by="final_amount",ascending=False).head(10)

## Lowest-value orders
df.sort_values(by="final_amount",ascending=True).head(10)

#######     GROUPBY   #######
## Revenue by category
category_revenue = (df.groupby("category")["final_amount"].sum().sort_values(ascending=False))
category_revenue

## Average revenue by category
df.groupby("category")["final_amount"].mean()

## Number of orders by category
df.groupby("category")["order_id"].count()

###########     AGGREGATION     #########
## Multiple aggregations
category_summary = df.groupby("category").agg(
    total_revenue=("final_amount", "sum"),
    average_order_value=("final_amount", "mean"),
    total_orders=("order_id", "count"),
    average_rating=("customer_rating", "mean")
)

category_summary

############   Apply FUNCTION   ###########
## Create customer/order value segment
def order_segment(value):
    if value >= 5000:
        return "High Value"
    elif value >= 2000:
        return "Medium Value"
    else:
        return "Low Value"

## Apply function
df["order_segment"] = df["final_amount"].apply(order_segment)

df[["final_amount", "order_segment"]].head(10)

############        FEATURE ENGINEERING     ##########
## Year
df["year"] = df["order_date"].dt.year
df["year"]

## month
df["month"] = df["order_date"].dt.month
df["month"]

## month name
df["month_name"] = df["order_date"].dt.month_name()
df["month_name"]

## weekday
df["weekday"] = df["order_date"].dt.day_name()

## Recalculate revenue
df["calculated_revenue"] = (
    df["product_price"] *
    df["quantity"] *
    (1 - df["discount_pct"] / 100)
)

df["calculated_revenue"] = df["calculated_revenue"].round(2)

###########    BUSINESS KPIs    ###########
## Total revenue
total_revenue = df["final_amount"].sum()
print("Total Revenue:", round(total_revenue, 2))

## Total orders
total_orders = df["order_id"].nunique()
print("Total Orders:", total_orders)

## Average Order Value
average_order_value = df["final_amount"].mean()

print("Average Order Value:", round(average_order_value, 2))

## Average rating
average_rating = df["customer_rating"].mean()
print("Average Rating:", round(average_rating, 2))

###########    NUMPY   ############
## Array creation
revenue_array = np.array(df["final_amount"])

revenue_array[:10]

## array properties
print("Shape:", revenue_array.shape)
print("Size:", revenue_array.size)
print("Data type:", revenue_array.dtype)

## Indexing
revenue_array = np.array(df["final_amount"])

revenue_array[0]

###########  Slicing  ##########
# first ten transaction amounts
revenue_array[:10]

##########  Boolean indexing  ##########
high_revenue = revenue_array[revenue_array > 5000]

high_revenue

##########  Broadcasting   ##########
price_array = np.array([100, 200, 300, 400])
price_with_tax = price_array * 1.18
price_with_tax

########### Reshaping  ############
sales = np.array(df["final_amount"].head(12))
sales_matrix = sales.reshape(3, 4)
sales_matrix

sales_matrix.shape

#############  Mathematical functions  ################
print("Sum:", np.sum(revenue_array))
print("Mean:", np.mean(revenue_array))
print("Minimum:", np.min(revenue_array))
print("Maximum:", np.max(revenue_array))

###############  statistical functions  ###########
print("Mean:", np.mean(revenue_array))
print("Median:", np.median(revenue_array))
print("Standard Deviation:", np.std(revenue_array))
print("Variance:", np.var(revenue_array))

############  Matrix operations  ##########
matrix_data = df[
    ["product_price", "quantity", "discount_pct", "customer_rating"]
].head(4).to_numpy()

matrix_data

matrix_data.shape

# Matrix transpose
matrix_data.T

# Matrix multiplication
A = matrix_data
B = matrix_data.T

result = np.dot(A, B)

result

############  OUTLIER DETECTION  ############
## IQR method
Q1 = df["final_amount"].quantile(0.25)
Q3 = df["final_amount"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df["final_amount"] < lower_bound) |
    (df["final_amount"] > upper_bound)
]

print("Number of outliers:", len(outliers))

#############    DATA VISUALIZATION   ###########
## LINE CHART
monthly_revenue = (
    df.groupby("month")["final_amount"]
    .sum()
)

plt.figure(figsize=(10,5))

plt.plot(
    monthly_revenue.index,
    monthly_revenue.values,
    marker="o"
)

plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.grid(True)

plt.show()

## BAR CHART
category_revenue = (
    df.groupby("category")["final_amount"]
    .sum()
    .sort_values(ascending=False)
)

plt.figure(figsize=(9,5))

plt.bar(
    category_revenue.index,
    category_revenue.values
)

plt.title("Revenue by Category")
plt.xlabel("Category")
plt.ylabel("Revenue")
plt.xticks(rotation=45)

plt.show()

## HISTOGRAM
plt.figure(figsize=(8,5))

plt.hist(
    df["final_amount"],
    bins=30
)

plt.title("Distribution of Order Values")
plt.xlabel("Final Amount")
plt.ylabel("Frequency")

plt.show()

## SCATTER PLOT
plt.figure(figsize=(8,5))

plt.scatter(
    df["product_price"],
    df["final_amount"],
    alpha=0.5
)

plt.title("Product Price vs Final Amount")
plt.xlabel("Product Price")
plt.ylabel("Final Amount")

plt.show()

## BOX PLOT
plt.figure(figsize=(8,5))

sns.boxplot(
    x=df["final_amount"]
)

plt.title("Order Value Distribution and Outliers")
plt.xlabel("Final Amount")

plt.show()

## COUNT PLOT
# To compare the frequency of different order-status categories.
plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="order_status"
)

plt.title("Orders by Status")
plt.xlabel("Order Status")
plt.ylabel("Number of Orders")

plt.show()

## HEATMAP
numeric_columns = [
    "product_price",
    "quantity",
    "discount_pct",
    "gross_amount",
    "discount_amount",
    "final_amount",
    "customer_rating"
]

correlation = df[numeric_columns].corr()

plt.figure(figsize=(10,7))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.show()

## PIE CHART
status_counts = df["order_status"].value_counts()

plt.figure(figsize=(7,7))

plt.pie(
    status_counts.values,
    labels=status_counts.index,
    autopct="%1.1f%%"
)

plt.title("Order Status Distribution")

plt.show()

## CATEGORY vs RATING BOX PLOT
plt.figure(figsize=(10,6))

sns.boxplot(
    data=df,
    x="category",
    y="customer_rating"
)

plt.title("Customer Rating Distribution by Category")
plt.xlabel("Category")
plt.ylabel("Customer Rating")
plt.xticks(rotation=45)

plt.show()

############  MORE BUSINESS ANALYSIS  ############
## Revenue by city
city_revenue = (
    df.groupby("city")["final_amount"]
    .sum()
    .sort_values(ascending=False)
)

city_revenue

## Revenue by payment method
payment_analysis = df.groupby("payment_method").agg(
    total_orders=("order_id", "count"),
    total_revenue=("final_amount", "sum"),
    average_order_value=("final_amount", "mean")
)

payment_analysis.sort_values(
    "total_revenue",
    ascending=False
)

## Revenue by order status
status_analysis = df.groupby("order_status").agg(
    total_orders=("order_id", "count"),
    total_revenue=("final_amount", "sum")
)

status_analysis

## Revenue by order segment
segment_analysis = (
    df.groupby("order_segment")["final_amount"]
    .agg(["count", "sum", "mean"])
)

segment_analysis

## Category with highest rating
category_rating = (
    df.groupby("category")["customer_rating"]
    .mean()
    .sort_values(ascending=False)
)

category_rating

## CANCELLATION & RETURN RATE
cancellation_rate = (
    (df["order_status"] == "Cancelled").mean() * 100
)

return_rate = (
    (df["order_status"] == "Returned").mean() * 100
)

print("Cancellation Rate:", round(cancellation_rate, 2), "%")
print("Return Rate:", round(return_rate, 2), "%")

############# end ############

df.to_csv("Hotel_Booking_Cleaned.csv", index=False)

from google.colab import files

files.download("Hotel_Booking_Cleaned.csv")